language: cpp
sudo: required

branches:
  only:
  - master

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: gcc
    - os: linux
      dist: bionic
      compiler: gcc
    - os: linux
      dist: xenial
      compiler: clang
    - os: osx
      compiler: clang
      osx_image: xcode11.4
      env:
        - CMAKE_PREFIX_PATH=/usr/local/opt/qt5:/usr/local/opt/openssl
    - os: osx
      compiler: clang
      osx_image: xcode9.4
      env:
        - CMAKE_PREFIX_PATH=/usr/local/opt/qt5:/usr/local/opt/openssl
      
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew unlink python@2;
      brew upgrade cmake qt5 python3 openssl git;
      brew install qscintilla2;
    else
      sudo apt-get -qq update;
    fi

before_script:
  - mkdir build
  - cd build
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      cmake .. -DALL=ON -DWITH_SCINTILLA=ON -DWITH_DISTORM_LINK_STATICALLY=ON;
    else
      cmake .. -DALL=ON -DWITH_SCINTILLA=ON;
    fi

script: make

addons:
  apt:
    packages:
    - cmake
    - git
    - libdistorm3-dev
    - libqt5concurrent5
    - libqt5gui5
    - libqt5network5
    - libqt5scintilla2-dev
    - libqt5svg5-dev
    - libqt5widgets5
    - libqt5xmlpatterns5-dev
    - libssl-dev
    - python2.7-dev
    - python3-dev
    - qtbase5-dev
