version: 3.7.2.rc.{build}

skip_commits:
  files:
    - .travis.yml
    - INSTALL
    - README.md
    - Build-process.md
    - unittests/*
    - LICENCE
    - todo

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      QTDIR: 'C:\Qt\5.15.2\msvc2019_64'
      OPENSSLDIR: 'C:\OpenSSL-v111-Win64'
      PATH: '%QTDIR%\bin;%PATH%'
      QSCINTILLA_VERSION: '2.13.1'
      compiler: vs2017
      platform: x64
      config: Release

install:
- call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
- git submodule update --init --recursive
- powershell -command "msbuild ext\distorm\make\win32\distorm.sln  /p:Configuration=dll /p:Platform=x64 /p:PlatformToolset=v141 /p:WindowsTargetPlatformVersion=10.0.17763.0"
- ps: $source = "https://www.riverbankcomputing.com/static/Downloads/QScintilla/$($env:QSCINTILLA_VERSION)/QScintilla_src-$($env:QSCINTILLA_VERSION).zip"
- ps: $destination = "QScintilla.zip"
- ps: Invoke-WebRequest $source -OutFile $destination
- 7z x .\QScintilla.zip -o.\ext\
- ps: ren "ext\QScintilla_src-$($env:QSCINTILLA_VERSION)" QScintilla_gpl
- ps: pushd ext\QScintilla_gpl\src
- qmake
- nmake
- ps: popd
- ps: popd
- ps: popd

before_build:
- mkdir build
- cd build
- cmake ../ -DALL=ON -DWITH_SCINTILLA=ON -G "NMake Makefiles" "-DCMAKE_PREFIX_PATH=%QTDIR%" -DOPENSSL_ROOT_DIR=%OPENSSLDIR% -DOPENSSL_CRYPTO_LIBRARY="%OPENSSLDIR%\lib\libcrypto.lib"
build_script:
- nmake
- cd ..

after_build:
- powershell -exec bypass -File win_package.ps1 %QTDIR% %compiler% %OPENSSLDIR%
- ps: ren package "pip3line_$($env:APPVEYOR_BUILD_VERSION)_win_x64"
- 7z a pip3line_%APPVEYOR_BUILD_VERSION%_win_x64.zip pip3line_%APPVEYOR_BUILD_VERSION%_win_x64

artifacts:
- path: pip3line_$(APPVEYOR_BUILD_VERSION)_win_x64.zip
  name: Pip3line

deploy:
- description: 'Pip3line windows binaries for x64'
  provider: GitHub
  auth_token:
    secure: 9fnQrJR6a2T86409RrK9X5Bq9C2+PP5LuN9uSJivbhFbC+MxGE0CZx2nqObe55Ar
  artifact: pip3line_$(APPVEYOR_BUILD_VERSION)_win_x64.zip
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true

