.\" Manpage for pip3line
.\" Contact gabriel.caudrelier@gmail.com to correct errors or typos.
.TH man 1 "13 November 2018" "1.0" "pip3line man page"
.SH NAME
pip3line - Launch the main gui for Pip3line 
.SH SYNOPSIS
pip3line [options]
.SH DESCRIPTION
pip3line is a Swiss Army knife for raw bytes manipulation & interception.
.SH OPTIONS
None
.SH SEE ALSO
pip3linecmd(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Gabriel Caudrelier (gabriel.caudrelier@gmail.com)
